// Auto-generated by make_combine_histograms.py
// Load in ROOT with:  root -l /Users/albertodufour/code/DY2026/restriction_table/tmp_hists/histograms_cje_view.C
//
void histograms_cje_view() {
    TFile *f = TFile::Open("/Users/albertodufour/code/DY2026/restriction_table/tmp_hists/histograms_cje.root");
    TDirectory *dir = (TDirectory*)f->Get("triple_DY");

    const char* procs[] = {"sm","quad_cje","sm_lin_quad_cje","data_obs"};
    Color_t cols[]      = {4, 2, 8, 1};
    Style_t lines[]     = {1, 2, 9, 1};
    Width_t widths[]    = {2, 2, 2, 1};

    TCanvas *c = new TCanvas("c_triple_DY","triple_DY  cje  C=1.0",900,600);
    c->SetLogy();
    gStyle->SetOptStat(0);
    TLegend *leg = new TLegend(0.62,0.65,0.92,0.88);

    TH1 *href = nullptr;
    for (int i = 0; i < 4; i++) {
        TH1 *h = (TH1*)dir->Get(procs[i]);
        if (!h) continue;
        h->SetLineColor(cols[i]);
        h->SetLineStyle(lines[i]);
        h->SetLineWidth(widths[i]);
        h->SetFillStyle(0);
        leg->AddEntry(h, procs[i], "l");
        if (!href) { h->Draw("HIST"); href = h; }
        else        h->Draw("HIST SAME");
    }
    leg->Draw();
    c->SaveAs("/Users/albertodufour/code/DY2026/restriction_table/tmp_hists/histograms_cje_cje.pdf");
}
